<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
interface SessionResponse { data: { authenticated:boolean; user?: { role:string } } }
interface AuditLog { id:string; action:string; target_type:string; target_id:string|null; created_at:string; allowed_users:{email:string|null;figma_handle:string|null}|null }
interface AuditResponse { data: { logs:AuditLog[]; total:number; page:number } }
const { data: session } = await useFetch<SessionResponse>('/api/auth/session')
if (session.value?.data?.user?.role !== 'admin') await navigateTo('/library')
const { data } = await useFetch<AuditResponse>('/api/admin/audit-logs')
</script>
<template><div class="admin-shell"><header class="toolbar"><NuxtLink class="identity" to="/library">Content Library</NuxtLink><nav><NuxtLink to="/admin/users">Users</NuxtLink><NuxtLink to="/admin/audit-log" aria-current="page">Audit log</NuxtLink></nav><span class="count">{{ data?.data.total ?? 0 }} events</span><NuxtLink class="close" to="/library" aria-label="Close administration"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5l14 14M19 5 5 19" /></svg></NuxtLink></header><main><section class="intro"><p>System history</p><h1>Every important<br>change, recorded.</h1></section><div class="labels" aria-hidden="true"><span>When</span><span>Action</span><span>Person</span><span>Target</span></div><ol><li v-for="log in data?.data.logs" :key="log.id"><time>{{ new Date(log.created_at).toLocaleString() }}</time><strong>{{ log.action.replace('_',' ') }}</strong><span>{{ log.allowed_users?.figma_handle ?? log.allowed_users?.email ?? 'System' }}</span><span>{{ log.target_type }}<small>{{ log.target_id ?? '—' }}</small></span></li></ol></main></div></template>
<style scoped>.admin-shell{--space:clamp(14px,1.25vw,24px);--ink:#111;--muted:rgb(17 17 17/.48);min-height:100vh;color:var(--ink);background:#f1f0ec;font-size:14px}.toolbar{position:sticky;z-index:3;top:0;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--space);padding:var(--space);background:rgb(241 240 236/.94);backdrop-filter:blur(14px)}.identity{font-weight:760;letter-spacing:-.025em;text-decoration:none}.toolbar nav{display:flex;gap:var(--space)}.toolbar nav a,.count{color:var(--muted);text-decoration:none}.toolbar nav [aria-current=page]{color:var(--ink)}.count{text-align:right}.close{width:44px;height:44px;margin-top:-10px;justify-self:end;display:grid;place-items:center;border-radius:50%;background:#e4e2dc;transition-property:scale,opacity;transition-duration:150ms}.close:hover{opacity:.65}.close:active{scale:.96}.close svg{width:22px;fill:none;stroke:currentColor;stroke-width:1.7}main{padding:clamp(4rem,9vw,9rem) var(--space) 6rem}.intro{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--space);margin-bottom:clamp(5rem,11vw,11rem)}.intro p{margin:0;color:var(--muted)}h1{grid-column:2/5;margin:0;font-size:clamp(3.5rem,8.4vw,9rem);font-weight:600;letter-spacing:-.065em;line-height:.86}.labels,li{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:var(--space)}.labels{padding-bottom:10px;color:var(--muted);font-size:12px}ol{margin:0;padding:0;list-style:none}li{padding:14px 0;border-top:1px solid rgb(17 17 17/.18)}li strong{font-weight:550;text-transform:capitalize}time,li>span{color:var(--muted)}li span:last-child{display:grid;color:var(--ink)}small{overflow:hidden;color:var(--muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}:is(a):focus-visible{outline:2px solid currentColor;outline-offset:3px}.toolbar a:hover{opacity:.55}@media(max-width:720px){.toolbar{grid-template-columns:1fr auto}.toolbar nav{grid-row:2}.count{display:none}.close{grid-column:2;grid-row:1/3}.intro{grid-template-columns:1fr}.intro p,h1{grid-column:1}h1{font-size:clamp(3.2rem,16vw,6rem)}.labels{display:none}li{grid-template-columns:1fr 1fr}li span:last-child{grid-column:1/-1}}@media(prefers-reduced-motion:reduce){.close{transition:none}.close:active{scale:1}}</style>
