<script setup lang="ts">
import type { VideoComposerSettings, VideoTemplate } from '~/types/video-composer'
import VideoRangeInput from '~/components/video-composer/VideoRangeInput.vue'

const props = defineProps<{ modelValue: VideoComposerSettings; template?: VideoTemplate }>()
const emit = defineEmits<{ 'update:modelValue': [value: VideoComposerSettings] }>()
const set = <K extends keyof VideoComposerSettings>(key: K, value: VideoComposerSettings[K]) => emit('update:modelValue', { ...props.modelValue, [key]: value })
const optionLabel = (value: string) => value.charAt(0).toUpperCase() + value.slice(1)
const formatRows = (distance: number) => Number((distance / 100).toFixed(2)).toString()
const tiltModes: { value: VideoComposerSettings['tiltMode']; label: string }[] = [
  { value: 'off', label: 'Off' }, { value: 'fan', label: 'Fan' }, { value: 'uniform', label: 'Uniform' }, { value: 'alternate', label: 'Alt' }
]
const easings: { value: VideoComposerSettings['easing']; label: string }[] = [
  { value: 'flow', label: 'Flow' }, { value: 'glide', label: 'Glide' }, { value: 'linear', label: 'Linear' }, { value: 'ease', label: 'Ease' }, { value: 'sweep', label: 'Sweep' }, { value: 'smooth', label: 'Smooth' }
]
const directionOptions = [
  { value: 'up', label: 'Up' }, { value: 'down', label: 'Down' }, { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }
] as const
const focusOptions = computed(() => props.modelValue.direction === 'left' || props.modelValue.direction === 'right'
  ? [{ value:'center',label:'Center' },{ value:'start',label:'Left' },{ value:'end',label:'Right' }] as const
  : [{ value:'center',label:'Center' },{ value:'start',label:'Top' },{ value:'end',label:'Bottom' }] as const)
const resetCarousel = () => emit('update:modelValue', { ...props.modelValue, direction:'up',gap:40,tilt:0,scaleCenter:false,tiltMode:'off',easing:'glide',cornerRadius:0,distance:100,centerScale:1.4,fade:0,offsetX:0,offsetY:0,scaleFocus:'center',solo:false,visibleCount:6,planeSize:600,cycles:1,secondsPerSlide:1.6,staggerFrames:2,delayFrames:0 })
const isCarousel3d = computed(() => props.template?.collection === 'carousel-3d')
const isGrid = computed(() => props.template?.collection === 'grid')
const isOrbit = computed(() => props.template?.collection === 'orbit')
const isGlobe = computed(() => props.template?.collection === 'globe')
const isScale = computed(() => props.template?.collection === 'scale')
const isStories = computed(() => props.template?.collection === 'stories')
const isFlicker = computed(() => props.template?.collection === 'flicker')
const isTest = computed(() => props.template?.collection === 'test')
const isSwipeDepth = computed(() => props.template?.collection === 'swipe-depth')
const resetCarousel3d = () => emit('update:modelValue', { ...props.modelValue, visibleCount:12,cycles:1,cycleDegrees:360,distance:1300,secondsPerSlide:8,reverse:false,planeSize:400,planeRotation:0,rotationX:30,rotationY:38,rotationZ:0,orbitRadius:280,perspective:140,cornerRadius:0,fade:0,offsetX:0,offsetY:0,easing:'linear',flipMaterial:'lit',flipLightIntensity:200,flipRoughness:72 })
const resetGrid = () => emit('update:modelValue', { ...props.modelValue, visibleCount:35,flipGridColumns:7,flipGridRows:5,flipGridGap:24,planeSize:100,centerScale:2.1,secondsPerSlide:2.4,delaySeconds:.8,cycles:6,cornerRadius:8,offsetX:0,offsetY:0,easing:'smooth',backgroundColor:'#111111',fit:'cover',driftDirection:'left',driftAmount:16,gridMoveDistance:300,gridStaggerCurve:'linear',gridLayout:'flat',gridTubeBend:'outside',gridTubeMotion:'continuous',gridTubeStepRotation:20,gridTubeEmphasisStyle:'stable',gridCameraZoom:100,gridTubeStagger:0,gridScatter:0,gridRotationVariance:0,gridScaleVariance:0,gridEmphasis:'none',gridEmphasisAmount:0,gridEmphasisCurve:'smooth' })
const resetOrbit = () => emit('update:modelValue', { ...props.modelValue, visibleCount:7,cycles:1,cycleDegrees:360,secondsPerSlide:8,delaySeconds:0,reverse:false,planeSize:370,rotationX:0,rotationY:0,rotationZ:0,orbitRadius:420,perspective:100,cornerRadius:0,fade:0,offsetX:0,offsetY:0,easing:'sweep' })
const resetGlobe = () => emit('update:modelValue', { ...props.modelValue, visibleCount:40,orbitRadius:355,globeMinScale:10,globeMaxScale:20,distance:1000,perspective:100,fade:0,cornerRadius:0,offsetX:0,offsetY:0,rotationX:0,rotationY:0,rotationZ:0,cycles:1,secondsPerSlide:7,cycleDegrees:360,delaySeconds:0,globeStops:8,reverse:false,globeAxis:'y',globeMotion:'continuous',globeShuffle:false,globeFaceCamera:true,globeShowBackfaces:true,globeFlipImage:false,planeSize:1000,easing:'linear' })
const resetScale = () => emit('update:modelValue', { ...props.modelValue, visibleCount:10,secondsPerSlide:2,planeSize:100,cornerRadius:0,spin:0,staggerSeconds:.4,scaleStyle:'bloom',growFrom:'center',imageFit:'fit',offsetX:0,offsetY:0 })
const resetStories = () => emit('update:modelValue', { ...props.modelValue, visibleCount:8,cycles:1,loop:true,secondsPerSlide:13.3,delaySeconds:.33,direction:'right',cornerRadius:6,offsetX:0,offsetY:0,storiesBigScale:115,storiesBigDrift:40,storiesThumbSize:85,storiesThumbAspect:'1:1',storiesContainerOpacity:40,storiesContainerBlur:60,storiesSelectorPad:5,storiesSelectorStroke:2,storiesDimAmount:20,easing:'smooth' })
const resetSwipeDepth = () => emit('update:modelValue', { ...props.modelValue, visibleCount:6,cycles:1,loop:true,direction:'left',swipeAlternating:true,secondsPerSlide:6,planeSize:520,gap:90,distance:85,perspective:100,cornerRadius:0,fade:30,tilt:7,offsetX:0,offsetY:0,easing:'sweep',scaleCenter:false,solo:false })
const resetFlicker = () => emit('update:modelValue', { ...props.modelValue, visibleCount:6,delaySeconds:0,cycles:1,flickerEffect:'off',flickerPacing:'equal',offsetX:0,offsetY:0,driftDirection:'up',secondsPerSlide:6,scaleDirection:'forward',planeSize:100,driftAmount:30,scaleAmount:30,cornerRadius:0,fit:'cover',easing:'smooth' })
</script>

<template>
  <section class="video-panel video-inspector">
    <div class="video-panel-scroll">
    <header><h2 class="filter-overlay-title">Settings</h2></header>
    <fieldset><legend>Loop</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.loop" @click="set('loop',true)">On</button><button type="button" :aria-pressed="!modelValue.loop" @click="set('loop',false)">Off</button></div></fieldset>
    <fieldset v-if="template?.renderer === 'webgl' && !isCarousel3d && !isGrid && !isOrbit && !isGlobe && !isScale && !isSwipeDepth"><legend>Direction</legend><div class="video-choice-row"><button v-for="option in directionOptions" :key="option.value" type="button" :aria-pressed="modelValue.direction === option.value" @click="set('direction', option.value)">{{ option.label }}</button></div></fieldset>
    <template v-if="isStories">
      <fieldset><legend>Direction</legend><div class="video-choice-row"><button v-for="option in [...directionOptions].reverse()" :key="option.value" type="button" :aria-pressed="modelValue.direction === option.value" @click="set('direction',option.value)">{{ option.label }}</button></div></fieldset>
      <fieldset><legend>Thumbnail aspect</legend><div class="video-choice-row"><button v-for="value in ['1:1','3:4','4:3'] as const" :key="value" type="button" :aria-pressed="modelValue.storiesThumbAspect === value" @click="set('storiesThumbAspect',value)">{{ value }}</button></div></fieldset>
      <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="3" max="12" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
      <div class="video-control-pair"><label><span>Active size <output>{{ modelValue.storiesBigScale }}%</output></span><VideoRangeInput min="100" max="200" :value="modelValue.storiesBigScale" @input="set('storiesBigScale',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Active drift <output>{{ modelValue.storiesBigDrift }}</output></span><VideoRangeInput min="0" max="200" :value="modelValue.storiesBigDrift" @input="set('storiesBigDrift',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <div class="video-control-pair"><label><span>Thumbnail size <output>{{ modelValue.storiesThumbSize }}</output></span><VideoRangeInput min="40" max="200" :value="modelValue.storiesThumbSize" @input="set('storiesThumbSize',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="30" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <div class="video-control-pair"><label><span>Rail opacity <output>{{ modelValue.storiesContainerOpacity }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.storiesContainerOpacity" @input="set('storiesContainerOpacity',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Rail blur <output>{{ modelValue.storiesContainerBlur }}</output></span><VideoRangeInput min="0" max="100" :value="modelValue.storiesContainerBlur" @input="set('storiesContainerBlur',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <div class="video-control-pair"><label><span>Selector padding <output>{{ modelValue.storiesSelectorPad }}</output></span><VideoRangeInput min="0" max="20" step="0.5" :value="modelValue.storiesSelectorPad" @input="set('storiesSelectorPad',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Selector stroke <output>{{ modelValue.storiesSelectorStroke }}</output></span><VideoRangeInput min="0" max="3" step="0.5" :value="modelValue.storiesSelectorStroke" @input="set('storiesSelectorStroke',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <label><span>Inactive dim <output>{{ modelValue.storiesDimAmount }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.storiesDimAmount" @input="set('storiesDimAmount',Number(($event.target as HTMLInputElement).value))" /></label>
      <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <fieldset><legend>Animation</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles.toFixed(2) }}</output></span><VideoRangeInput min="0.25" max="8" step="0.25" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="2" max="60" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Delay <output>{{ modelValue.delaySeconds.toFixed(2) }}s</output></span><VideoRangeInput min="0" max="2" step="0.05" :value="modelValue.delaySeconds" @input="set('delaySeconds',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
      <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing',option.value)">{{ option.label }}</button></div></fieldset>
      <button class="video-reset" type="button" @click="resetStories">Reset stories values</button>
    </template>
    <template v-if="isFlicker">
      <fieldset><legend>Image fit</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.fit === 'contain'" @click="set('fit','contain')">Fit</button><button type="button" :aria-pressed="modelValue.fit === 'cover'" @click="set('fit','cover')">Fill</button></div></fieldset>
      <fieldset><legend>Pacing</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.flickerPacing === 'equal'" @click="set('flickerPacing','equal')">Equal</button><button type="button" :aria-pressed="modelValue.flickerPacing === 'eased'" @click="set('flickerPacing','eased')">Eased</button></div></fieldset>
      <fieldset><legend>Effect</legend><div class="video-choice-row"><button v-for="value in ['off','scale','drift'] as const" :key="value" type="button" :aria-pressed="modelValue.flickerEffect === value" @click="set('flickerEffect',value)">{{ optionLabel(value) }}</button></div></fieldset>
      <fieldset v-if="modelValue.flickerEffect === 'scale'"><legend>Scale direction</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.scaleDirection === 'forward'" @click="set('scaleDirection','forward')">Forward</button><button type="button" :aria-pressed="modelValue.scaleDirection === 'reverse'" @click="set('scaleDirection','reverse')">Reverse</button></div></fieldset>
      <fieldset v-if="modelValue.flickerEffect === 'drift'"><legend>Drift direction</legend><div class="video-choice-row"><button v-for="option in directionOptions" :key="option.value" type="button" :aria-pressed="modelValue.driftDirection === option.value" @click="set('driftDirection',option.value)">{{ option.label }}</button></div></fieldset>
      <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="30" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
      <label><span>Plane size <output>{{ modelValue.planeSize }}%</output></span><VideoRangeInput min="10" max="200" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
      <label v-if="modelValue.flickerEffect === 'scale'"><span>Scale amount <output>{{ modelValue.scaleAmount }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.scaleAmount" @input="set('scaleAmount',Number(($event.target as HTMLInputElement).value))" /></label>
      <label v-if="modelValue.flickerEffect === 'drift'"><span>Drift amount <output>{{ modelValue.driftAmount }}%</output></span><VideoRangeInput min="0" max="200" :value="modelValue.driftAmount" @input="set('driftAmount',Number(($event.target as HTMLInputElement).value))" /></label>
      <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="200" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
      <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <fieldset><legend>Animation</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles.toFixed(2) }}</output></span><VideoRangeInput min="0.25" max="8" step="0.25" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="1" max="60" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Delay <output>{{ modelValue.delaySeconds.toFixed(2) }}s</output></span><VideoRangeInput min="0" max="5" step="0.05" :value="modelValue.delaySeconds" @input="set('delaySeconds',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
      <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing',option.value)">{{ option.label }}</button></div></fieldset>
      <button class="video-reset" type="button" @click="resetFlicker">Reset One Shot values</button>
    </template>
    <template v-if="template?.renderer === 'webgl' || isScale">
      <template v-if="isGrid">
        <fieldset><legend>Image fit</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.fit === 'contain'" @click="set('fit','contain')">Fit</button><button type="button" :aria-pressed="modelValue.fit === 'cover'" @click="set('fit','cover')">Fill</button></div></fieldset>
        <fieldset><legend>Layout</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.gridLayout !== 'tube'" @click="set('gridLayout','flat')">Flat</button><button type="button" :aria-pressed="modelValue.gridLayout === 'tube'" @click="set('gridLayout','tube')">Curved</button></div></fieldset>
        <fieldset v-if="modelValue.gridLayout === 'tube'"><legend>Bend</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.gridTubeBend !== 'inside'" @click="set('gridTubeBend','outside')">Outside</button><button type="button" :aria-pressed="modelValue.gridTubeBend === 'inside'" @click="set('gridTubeBend','inside')">Inside</button></div></fieldset>
        <fieldset v-if="modelValue.gridLayout === 'tube'"><legend>Motion</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.gridTubeMotion !== 'stepped'" @click="set('gridTubeMotion','continuous')">Continuous</button><button type="button" :aria-pressed="modelValue.gridTubeMotion === 'stepped'" @click="set('gridTubeMotion','stepped')">Stepped</button></div></fieldset>
        <label><span>Camera zoom <output>{{ modelValue.gridCameraZoom }}%</output></span><VideoRangeInput min="50" max="300" step="5" :value="modelValue.gridCameraZoom" @input="set('gridCameraZoom',Number(($event.target as HTMLInputElement).value))" /></label>
        <label v-if="modelValue.gridLayout === 'tube'"><span>{{ modelValue.gridTubeMotion === 'stepped' ? 'Motion stagger' : 'Stagger' }} <output>{{ modelValue.gridTubeStagger }}%</output></span><VideoRangeInput min="-100" max="100" step="5" :value="modelValue.gridTubeStagger" @input="set('gridTubeStagger',Number(($event.target as HTMLInputElement).value))" /></label>
        <fieldset v-if="modelValue.gridLayout === 'tube' && modelValue.gridTubeMotion === 'stepped'"><legend>Stagger curve</legend><div class="video-choice-row"><button v-for="curve in easings" :key="curve.value" type="button" :aria-pressed="(modelValue.gridStaggerCurve || 'linear') === curve.value" @click="set('gridStaggerCurve',curve.value)">{{ curve.label }}</button></div></fieldset>
        <fieldset><legend>Direction</legend><div class="video-choice-row"><button v-for="option in directionOptions" :key="option.value" type="button" :aria-pressed="modelValue.driftDirection === option.value" @click="set('driftDirection',option.value)">{{ option.label }}</button></div></fieldset>
        <label v-if="modelValue.gridLayout === 'tube' && modelValue.gridTubeMotion === 'stepped' && (modelValue.driftDirection === 'left' || modelValue.driftDirection === 'right')"><span>Step rotation <output>{{ modelValue.gridTubeStepRotation }}°</output></span><VideoRangeInput min="1" max="180" :value="modelValue.gridTubeStepRotation" @input="set('gridTubeStepRotation',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="4" max="60" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Columns <output>{{ modelValue.flipGridColumns }}</output></span><VideoRangeInput min="2" max="24" :value="modelValue.flipGridColumns" @input="set('flipGridColumns',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Rows <output>{{ modelValue.flipGridRows }}</output></span><VideoRangeInput min="2" max="18" :value="modelValue.flipGridRows" @input="set('flipGridRows',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <div class="video-control-pair"><label><span>Cell size <output>{{ modelValue.planeSize }}%</output></span><VideoRangeInput min="40" max="180" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Gap <output>{{ modelValue.flipGridGap }}%</output></span><VideoRangeInput min="0" max="50" step="0.5" :value="modelValue.flipGridGap" @input="set('flipGridGap',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Emphasis</legend><div class="video-choice-row"><button v-for="value in ['none','center','edges'] as const" :key="value" type="button" :aria-pressed="modelValue.gridEmphasis === value" @click="set('gridEmphasis',value)">{{ optionLabel(value) }}</button></div></fieldset>
        <fieldset v-if="modelValue.gridLayout === 'tube' && modelValue.gridEmphasis !== 'none'"><legend>Emphasis style</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.gridTubeEmphasisStyle !== 'rings'" @click="set('gridTubeEmphasisStyle','stable')">Stable</button><button type="button" :aria-pressed="modelValue.gridTubeEmphasisStyle === 'rings'" @click="set('gridTubeEmphasisStyle','rings')">Rings</button></div></fieldset>
        <label v-if="modelValue.gridEmphasis !== 'none'"><span>Emphasis amount <output>{{ modelValue.gridEmphasisAmount }}%</output></span><VideoRangeInput min="0" max="500" step="5" :value="modelValue.gridEmphasisAmount" @input="set('gridEmphasisAmount',Number(($event.target as HTMLInputElement).value))" /></label>
        <fieldset v-if="modelValue.gridEmphasis !== 'none'"><legend>Emphasis curve</legend><div class="video-choice-row video-choice-wrap"><button v-for="curve in easings" :key="curve.value" type="button" :aria-pressed="modelValue.gridEmphasisCurve === curve.value" @click="set('gridEmphasisCurve',curve.value)">{{ curve.label }}</button></div></fieldset>
        <div class="video-control-pair"><label><span>Scatter <output>{{ modelValue.gridScatter }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.gridScatter" @input="set('gridScatter',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Size variation <output>{{ modelValue.gridScaleVariance }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.gridScaleVariance" @input="set('gridScaleVariance',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <label><span>Rotation variation <output>{{ modelValue.gridRotationVariance }}°</output></span><VideoRangeInput min="0" max="45" :value="modelValue.gridRotationVariance" @input="set('gridRotationVariance',Number(($event.target as HTMLInputElement).value))" /></label>
        <div v-if="modelValue.gridLayout !== 'tube'" class="video-control-pair"><label><span>Card stagger <output>{{ modelValue.driftAmount }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.driftAmount" @input="set('driftAmount',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Move distance <output>{{ formatRows(modelValue.gridMoveDistance) }} rows</output></span><VideoRangeInput min="0" max="500" step="5" :value="modelValue.gridMoveDistance" @input="set('gridMoveDistance',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset v-if="modelValue.gridLayout !== 'tube'"><legend>Stagger curve</legend><div class="video-choice-row"><button v-for="curve in easings" :key="curve.value" type="button" :aria-pressed="(modelValue.gridStaggerCurve || 'linear') === curve.value" @click="set('gridStaggerCurve',curve.value)">{{ curve.label }}</button></div></fieldset>
        <label v-if="modelValue.gridLayout !== 'tube'"><span>Focus zoom <output>{{ modelValue.centerScale.toFixed(2) }}×</output></span><VideoRangeInput min="1" max="2.5" step="0.05" :value="modelValue.centerScale" @input="set('centerScale',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="100" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>{{ modelValue.gridLayout === 'tube' ? 'Motion timing' : 'Focus motion' }}</legend><div class="video-control-pair"><label><span>{{ modelValue.gridLayout === 'tube' ? modelValue.gridTubeMotion === 'stepped' ? 'Steps' : 'Loops' : 'Stops' }} <output>{{ modelValue.cycles }}</output></span><VideoRangeInput min="1" max="20" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>{{ modelValue.gridLayout === 'tube' ? modelValue.gridTubeMotion === 'stepped' ? 'Step duration' : 'Loop duration' : 'Travel' }} <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="0.5" max="10" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label v-if="modelValue.gridLayout !== 'tube' || modelValue.gridTubeMotion === 'stepped'"><span>Hold <output>{{ modelValue.delaySeconds.toFixed(1) }}s</output></span><VideoRangeInput min="0" max="5" step="0.1" :value="modelValue.delaySeconds" @input="set('delaySeconds',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset v-if="modelValue.gridLayout !== 'tube' || modelValue.gridTubeMotion === 'stepped'"><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing',option.value)">{{ option.label }}</button></div></fieldset>
        <button class="video-reset" type="button" @click="resetGrid">Reset grid values</button>
      </template>
      <template v-else-if="isSwipeDepth">
        <fieldset><legend>Direction</legend><div class="video-choice-row"><button v-for="option in directionOptions" :key="option.value" type="button" :aria-pressed="modelValue.direction === option.value" @click="set('direction',option.value)">{{ option.label }}</button></div></fieldset>
        <fieldset><legend>Swipe direction</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.swipeAlternating === false" @click="set('swipeAlternating',false)">One side</button><button type="button" :aria-pressed="modelValue.swipeAlternating !== false" @click="set('swipeAlternating',true)">Alternate</button></div></fieldset>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="20" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Plane size <output>{{ modelValue.planeSize }} px</output></span><VideoRangeInput min="100" max="1000" step="10" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Row spacing <output>{{ modelValue.gap }}</output></span><VideoRangeInput min="0" max="400" step="5" :value="modelValue.gap" @input="set('gap',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Depth spacing <output>{{ modelValue.distance }}</output></span><VideoRangeInput min="10" max="300" step="5" :value="modelValue.distance" @input="set('distance',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <label><span>Swipe rotation <output>{{ modelValue.tilt }}°</output></span><VideoRangeInput min="-45" max="45" :value="modelValue.tilt" @input="set('tilt',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Depth fade <output>{{ modelValue.fade }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.fade" @input="set('fade',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="200" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Animation</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles }}</output></span><VideoRangeInput min="1" max="6" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="1" max="30" step="0.5" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing',option.value)">{{ option.label }}</button></div></fieldset>
        <button class="video-reset" type="button" @click="resetSwipeDepth">Reset swipe depth values</button>
      </template>
      <template v-else-if="isTest">
        <fieldset><legend>Image fit</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.fit === 'contain'" @click="set('fit','contain')">Fit</button><button type="button" :aria-pressed="modelValue.fit === 'cover'" @click="set('fit','cover')">Fill</button></div></fieldset>
        <fieldset><legend>Material</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.flipMaterial === 'flat'" @click="set('flipMaterial','flat')">Flat</button><button type="button" :aria-pressed="modelValue.flipMaterial === 'lit'" @click="set('flipMaterial','lit')">Lit</button></div></fieldset>
        <div v-if="modelValue.flipMaterial === 'lit'" class="video-control-pair"><label><span>Light <output>{{ modelValue.flipLightIntensity }}%</output></span><VideoRangeInput min="0" max="200" :value="modelValue.flipLightIntensity" @input="set('flipLightIntensity',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Roughness <output>{{ modelValue.flipRoughness }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.flipRoughness" @input="set('flipRoughness',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Grid</legend><div class="video-control-pair"><label><span>Columns <output>{{ modelValue.flipGridColumns }}</output></span><VideoRangeInput min="1" max="6" :value="modelValue.flipGridColumns" @input="set('flipGridColumns',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Rows <output>{{ modelValue.flipGridRows }}</output></span><VideoRangeInput min="1" max="6" :value="modelValue.flipGridRows" @input="set('flipGridRows',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset><legend>Shuffle</legend><div class="video-choice-row"><button type="button" :aria-pressed="!modelValue.flipShuffle" @click="set('flipShuffle',false)">Off</button><button type="button" :aria-pressed="modelValue.flipShuffle" @click="set('flipShuffle',true)">On</button></div></fieldset>
        <div class="video-control-pair"><label><span>Grid gap <output>{{ modelValue.flipGridGap }}%</output></span><VideoRangeInput min="0" max="20" step="0.5" :value="modelValue.flipGridGap" @input="set('flipGridGap',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Stagger <output>{{ modelValue.flipStagger.toFixed(2) }}s</output></span><VideoRangeInput min="0" max="2" step="0.05" :value="modelValue.flipStagger" @input="set('flipStagger',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="30" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Plane size <output>{{ modelValue.planeSize }}%</output></span><VideoRangeInput min="10" max="150" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Perspective <output>{{ modelValue.perspective }}</output></span><VideoRangeInput min="50" max="300" step="5" :value="modelValue.perspective" @input="set('perspective',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="200" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Animation</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles.toFixed(2) }}</output></span><VideoRangeInput min="0.25" max="8" step="0.25" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="1" max="60" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Delay <output>{{ modelValue.delaySeconds.toFixed(2) }}s</output></span><VideoRangeInput min="0" max="5" step="0.05" :value="modelValue.delaySeconds" @input="set('delaySeconds',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing',option.value)">{{ option.label }}</button></div></fieldset>
      </template>
      <template v-else-if="isScale">
        <fieldset><legend>Scale style</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.scaleStyle === 'bloom'" @click="set('scaleStyle','bloom')">Bloom</button><button type="button" :aria-pressed="modelValue.scaleStyle === 'recede'" @click="set('scaleStyle','recede')">Recede</button></div></fieldset>
        <fieldset><legend>Grow from</legend><div class="video-choice-row"><button v-for="value in ['center','top','bottom','left','right'] as const" :key="value" type="button" :aria-pressed="modelValue.growFrom === value" @click="set('growFrom',value)">{{ optionLabel(value) }}</button></div></fieldset>
        <fieldset><legend>Image fit</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.imageFit === 'fit'" @click="set('imageFit','fit')">Fit</button><button type="button" :aria-pressed="modelValue.imageFit === 'fill'" @click="set('imageFit','fill')">Fill</button></div></fieldset>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="20" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Plane size <output>{{ modelValue.planeSize }}%</output></span><VideoRangeInput min="5" max="400" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Spin <output>{{ modelValue.spin }}°</output></span><VideoRangeInput min="-180" max="180" :value="modelValue.spin" @input="set('spin',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="200" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Motion</legend><div class="video-control-pair"><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="0.3" max="6" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Stagger <output>{{ modelValue.staggerSeconds.toFixed(2) }}s</output></span><VideoRangeInput min="0.05" max="3" step="0.05" :value="modelValue.staggerSeconds" @input="set('staggerSeconds',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <button class="video-reset" type="button" @click="resetScale">Reset scale values</button>
      </template>
      <template v-else-if="isGlobe">
        <fieldset><legend>Direction</legend><div class="video-choice-row"><button type="button" :aria-pressed="!modelValue.reverse" @click="set('reverse',false)">Forward</button><button type="button" :aria-pressed="modelValue.reverse" @click="set('reverse',true)">Reverse</button></div></fieldset>
        <fieldset><legend>Axis</legend><div class="video-choice-row video-axis-row"><button v-for="value in ['x','y','z'] as const" :key="value" type="button" :aria-pressed="modelValue.globeAxis === value" @click="set('globeAxis',value)">{{ value.toUpperCase() }}</button></div></fieldset>
        <fieldset><legend>Motion</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.globeMotion === 'continuous'" @click="set('globeMotion','continuous')">Continuous</button><button type="button" :aria-pressed="modelValue.globeMotion === 'stepped'" @click="set('globeMotion','stepped')">Stepped</button></div></fieldset>
        <fieldset><legend>Shuffle</legend><div class="video-choice-row"><button type="button" :aria-pressed="!modelValue.globeShuffle" @click="set('globeShuffle',false)">Off</button><button type="button" :aria-pressed="modelValue.globeShuffle" @click="set('globeShuffle',true)">On</button></div></fieldset>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="4" max="60" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Radius <output>{{ modelValue.orbitRadius }}</output></span><VideoRangeInput min="50" max="3000" step="5" :value="modelValue.orbitRadius" @input="set('orbitRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Min scale <output>{{ modelValue.globeMinScale }}%</output></span><VideoRangeInput min="1" max="100" :value="modelValue.globeMinScale" @input="set('globeMinScale',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Max scale <output>{{ modelValue.globeMaxScale }}%</output></span><VideoRangeInput min="1" max="200" :value="modelValue.globeMaxScale" @input="set('globeMaxScale',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <label><span>Distance <output>{{ modelValue.distance }}</output></span><VideoRangeInput min="0" max="10000" step="50" :value="modelValue.distance" @input="set('distance',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Perspective <output>{{ modelValue.perspective }}</output></span><VideoRangeInput min="10" max="300" step="5" :value="modelValue.perspective" @input="set('perspective',Number(($event.target as HTMLInputElement).value))" /></label>
        <fieldset><legend>Rotation</legend><div class="video-control-pair"><label><span>X <output>{{ modelValue.rotationX }}°</output></span><VideoRangeInput min="-90" max="90" :value="modelValue.rotationX" @input="set('rotationX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Y <output>{{ modelValue.rotationY }}°</output></span><VideoRangeInput min="-180" max="180" :value="modelValue.rotationY" @input="set('rotationY',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Z <output>{{ modelValue.rotationZ }}°</output></span><VideoRangeInput min="-90" max="90" :value="modelValue.rotationZ" @input="set('rotationZ',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="200" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Depth fade <output>{{ modelValue.fade }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.fade" @input="set('fade',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Facing</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.globeFaceCamera" @click="set('globeFaceCamera',true)">Camera</button><button type="button" :aria-pressed="!modelValue.globeFaceCamera" @click="set('globeFaceCamera',false)">Radial</button></div></fieldset>
        <fieldset><legend>Backfaces</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.globeShowBackfaces" @click="set('globeShowBackfaces',true)">Show</button><button type="button" :aria-pressed="!modelValue.globeShowBackfaces" @click="set('globeShowBackfaces',false)">Hide</button></div></fieldset>
        <fieldset><legend>Flip image</legend><div class="video-choice-row"><button type="button" :aria-pressed="!modelValue.globeFlipImage" @click="set('globeFlipImage',false)">Off</button><button type="button" :aria-pressed="modelValue.globeFlipImage" @click="set('globeFlipImage',true)">On</button></div></fieldset>
        <div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles.toFixed(2) }}</output></span><VideoRangeInput min="0.25" max="12" step="0.25" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="0.5" max="60" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <div class="video-control-pair"><label><span>Cycle angle <output>{{ modelValue.cycleDegrees }}°</output></span><VideoRangeInput min="30" max="720" :value="modelValue.cycleDegrees" @input="set('cycleDegrees',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Delay <output>{{ modelValue.delaySeconds.toFixed(2) }}s</output></span><VideoRangeInput min="0" max="5" step="0.05" :value="modelValue.delaySeconds" @input="set('delaySeconds',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <label v-if="modelValue.globeMotion === 'stepped'"><span>Stops <output>{{ modelValue.globeStops }}</output></span><VideoRangeInput min="2" max="30" :value="modelValue.globeStops" @input="set('globeStops',Number(($event.target as HTMLInputElement).value))" /></label>
        <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing', option.value)">{{ option.label }}</button></div></fieldset>
        <button class="video-reset" type="button" @click="resetGlobe">Reset globe values</button>
      </template>
      <template v-else-if="isOrbit">
        <fieldset><legend>Direction</legend><div class="video-choice-row"><button type="button" :aria-pressed="!modelValue.reverse" @click="set('reverse',false)">Forward</button><button type="button" :aria-pressed="modelValue.reverse" @click="set('reverse',true)">Reverse</button></div></fieldset>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="20" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Plane size <output>{{ modelValue.planeSize }} px</output></span><VideoRangeInput min="50" max="3000" step="10" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Orbit radius <output>{{ modelValue.orbitRadius }}</output></span><VideoRangeInput min="20" max="1000" step="5" :value="modelValue.orbitRadius" @input="set('orbitRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Perspective <output>{{ modelValue.perspective }}</output></span><VideoRangeInput min="10" max="300" step="5" :value="modelValue.perspective" @input="set('perspective',Number(($event.target as HTMLInputElement).value))" /></label>
        <fieldset><legend>Rotation</legend><div class="video-control-pair"><label><span>X <output>{{ modelValue.rotationX }}°</output></span><VideoRangeInput min="0" max="360" :value="modelValue.rotationX" @input="set('rotationX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Y <output>{{ modelValue.rotationY }}°</output></span><VideoRangeInput min="0" max="360" :value="modelValue.rotationY" @input="set('rotationY',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Z <output>{{ modelValue.rotationZ }}°</output></span><VideoRangeInput min="0" max="360" :value="modelValue.rotationZ" @input="set('rotationZ',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="500" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Depth fade <output>{{ modelValue.fade }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.fade" @input="set('fade',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" step="0.5" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Animation</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles.toFixed(2) }}</output></span><VideoRangeInput min="0.25" max="4" step="0.25" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="2" max="30" step="0.5" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Delay <output>{{ modelValue.delaySeconds.toFixed(2) }}s</output></span><VideoRangeInput min="0" max="5" step="0.05" :value="modelValue.delaySeconds" @input="set('delaySeconds',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing', option.value)">{{ option.label }}</button></div></fieldset>
        <button class="video-reset" type="button" @click="resetOrbit">Reset orbit values</button>
      </template>
      <template v-else-if="isCarousel3d">
        <fieldset><legend>Direction</legend><div class="video-choice-row"><button type="button" :aria-pressed="!modelValue.reverse" @click="set('reverse',false)">Forward</button><button type="button" :aria-pressed="modelValue.reverse" @click="set('reverse',true)">Reverse</button></div></fieldset>
        <label><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="40" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Plane size <output>{{ modelValue.planeSize }} px</output></span><VideoRangeInput min="100" max="800" step="10" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Plane rotation <output>{{ modelValue.planeRotation }}°</output></span><VideoRangeInput min="-180" max="180" :value="modelValue.planeRotation" @input="set('planeRotation',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Orbit radius <output>{{ modelValue.orbitRadius }}</output></span><VideoRangeInput min="0" max="800" step="10" :value="modelValue.orbitRadius" @input="set('orbitRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Distance <output>{{ modelValue.distance }}</output></span><VideoRangeInput min="200" max="5000" step="10" :value="modelValue.distance" @input="set('distance',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Perspective <output>{{ modelValue.perspective }}</output></span><VideoRangeInput min="50" max="350" step="10" :value="modelValue.perspective" @input="set('perspective',Number(($event.target as HTMLInputElement).value))" /></label>
        <fieldset><legend>Rotation</legend><div class="video-control-pair"><label><span>X <output>{{ modelValue.rotationX }}°</output></span><VideoRangeInput min="-90" max="90" :value="modelValue.rotationX" @input="set('rotationX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Y <output>{{ modelValue.rotationY }}°</output></span><VideoRangeInput min="-90" max="90" :value="modelValue.rotationY" @input="set('rotationY',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Z <output>{{ modelValue.rotationZ }}°</output></span><VideoRangeInput min="-360" max="360" :value="modelValue.rotationZ" @input="set('rotationZ',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset><legend>Material</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.flipMaterial === 'flat'" @click="set('flipMaterial','flat')">Flat</button><button type="button" :aria-pressed="modelValue.flipMaterial === 'lit'" @click="set('flipMaterial','lit')">Lit</button></div></fieldset>
        <div v-if="modelValue.flipMaterial === 'lit'" class="video-control-pair"><label><span>Light <output>{{ modelValue.flipLightIntensity }}%</output></span><VideoRangeInput min="0" max="200" :value="modelValue.flipLightIntensity" @input="set('flipLightIntensity',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Roughness <output>{{ modelValue.flipRoughness }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.flipRoughness" @input="set('flipRoughness',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="200" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
        <label><span>Depth fade <output>{{ modelValue.fade }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.fade" @input="set('fade',Number(($event.target as HTMLInputElement).value))" /></label>
        <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
        <fieldset><legend>Motion</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles }}</output></span><VideoRangeInput min="1" max="6" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Cycle angle <output>{{ modelValue.cycleDegrees }}°</output></span><VideoRangeInput min="30" max="360" step="30" :value="modelValue.cycleDegrees" @input="set('cycleDegrees',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="1" max="20" step="0.5" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
        <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing', option.value)">{{ option.label }}</button></div></fieldset>
        <button class="video-reset" type="button" @click="resetCarousel3d">Reset 3D carousel values</button>
      </template>
      <template v-else>
      <fieldset><legend>Scale center</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.scaleCenter" @click="set('scaleCenter',true)">On</button><button type="button" :aria-pressed="!modelValue.scaleCenter" @click="set('scaleCenter',false)">Off</button></div></fieldset>
      <fieldset v-if="modelValue.scaleCenter"><legend>Scale focus</legend><div class="video-choice-row"><button v-for="option in focusOptions" :key="option.value" type="button" :aria-pressed="modelValue.scaleFocus === option.value" @click="set('scaleFocus', option.value)">{{ option.label }}</button></div></fieldset>
      <label v-if="modelValue.scaleCenter"><span>Scale amount <output>{{ modelValue.centerScale.toFixed(2) }}×</output></span><VideoRangeInput min="1" max="2" step="0.05" :value="modelValue.centerScale" @input="set('centerScale',Number(($event.target as HTMLInputElement).value))" /></label>
      <fieldset><legend>Tilt</legend><div class="video-choice-row"><button v-for="option in tiltModes" :key="option.value" type="button" :aria-pressed="modelValue.tiltMode === option.value" @click="set('tiltMode', option.value)">{{ option.label }}</button></div></fieldset>
      <label v-if="modelValue.tiltMode !== 'off'"><span>Amount <output>{{ modelValue.tilt }}%</output></span><VideoRangeInput min="-100" max="100" :value="modelValue.tilt" @input="set('tilt',Number(($event.target as HTMLInputElement).value))" /></label>
      <fieldset><legend>Solo</legend><div class="video-choice-row"><button type="button" :aria-pressed="modelValue.solo" @click="set('solo',true)">On</button><button type="button" :aria-pressed="!modelValue.solo" @click="set('solo',false)">Off</button></div></fieldset>
      <label v-if="!modelValue.solo"><span>Count <output>{{ modelValue.visibleCount }}</output></span><VideoRangeInput min="2" max="20" :value="modelValue.visibleCount" @input="set('visibleCount',Number(($event.target as HTMLInputElement).value))" /></label>
      <label><span>Plane size <output>{{ modelValue.planeSize }} px</output></span><VideoRangeInput min="50" max="3000" step="10" :value="modelValue.planeSize" @input="set('planeSize',Number(($event.target as HTMLInputElement).value))" /></label>
      <label><span>Corner radius <output>{{ modelValue.cornerRadius }} px</output></span><VideoRangeInput min="0" max="500" :value="modelValue.cornerRadius" @input="set('cornerRadius',Number(($event.target as HTMLInputElement).value))" /></label>
      <label><span>Gap <output>{{ modelValue.gap }} px</output></span><VideoRangeInput min="0" max="1000" step="10" :value="modelValue.gap" @input="set('gap',Number(($event.target as HTMLInputElement).value))" /></label>
      <label><span>Edge fade <output>{{ modelValue.fade }}%</output></span><VideoRangeInput min="0" max="100" :value="modelValue.fade" @input="set('fade',Number(($event.target as HTMLInputElement).value))" /></label>
      <div class="video-control-pair"><label><span>Offset X <output>{{ modelValue.offsetX }}</output></span><VideoRangeInput min="-100" max="100" :value="modelValue.offsetX" @input="set('offsetX',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Offset Y <output>{{ modelValue.offsetY }}</output></span><VideoRangeInput min="-100" max="100" :value="modelValue.offsetY" @input="set('offsetY',Number(($event.target as HTMLInputElement).value))" /></label></div>
      <fieldset><legend>Motion</legend><div class="video-control-pair"><label><span>Cycles <output>{{ modelValue.cycles.toFixed(1) }}</output></span><VideoRangeInput min="0.5" max="3" step="0.5" :value="modelValue.cycles" @input="set('cycles',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Duration <output>{{ modelValue.secondsPerSlide.toFixed(1) }}s</output></span><VideoRangeInput min="0.5" max="5" step="0.1" :value="modelValue.secondsPerSlide" @input="set('secondsPerSlide',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Stagger <output>{{ modelValue.staggerFrames }}f</output></span><VideoRangeInput min="0" max="12" :value="modelValue.staggerFrames" @input="set('staggerFrames',Number(($event.target as HTMLInputElement).value))" /></label><label><span>Delay <output>{{ modelValue.delayFrames }}f</output></span><VideoRangeInput min="0" max="60" :value="modelValue.delayFrames" @input="set('delayFrames',Number(($event.target as HTMLInputElement).value))" /></label></div></fieldset>
      <fieldset><legend>Easing</legend><div class="video-choice-row"><button v-for="option in easings" :key="option.value" type="button" :aria-pressed="modelValue.easing === option.value" @click="set('easing', option.value)">{{ option.label }}</button></div></fieldset>
      <button class="video-reset" type="button" @click="resetCarousel">Reset carousel values</button>
      </template>
    </template>
    <fieldset v-if="template?.renderer !== 'webgl' && !isFlicker && !isStories && !isScale"><legend>Transition</legend><div class="video-choice-row"><button v-for="value in ['cut','fade']" :key="value" type="button" :aria-pressed="modelValue.transition === value" @click="set('transition', value as 'cut'|'fade')">{{ optionLabel(value) }}</button></div></fieldset>
    </div>
  </section>
</template>
