<script setup lang="ts">
interface Workspace { id:string; name:string; slug:string; role:string }
const root=ref<HTMLElement>();const trigger=ref<HTMLButtonElement>();const open=ref(false);const switchingId=ref('')
const {data}=await useFetch<{data:{currentId:string;workspaces:Workspace[]}}>('/api/workspaces')
const workspaces=computed(()=>data.value?.data.workspaces??[])
const currentId=computed(()=>data.value?.data.currentId??'')
const current=computed(()=>workspaces.value.find(workspace=>workspace.id===currentId.value))
const close=(restoreFocus=false)=>{open.value=false;if(restoreFocus)nextTick(()=>trigger.value?.focus())}
const switchWorkspace=async(workspace:Workspace)=>{if(workspace.id===currentId.value||switchingId.value)return close();switchingId.value=workspace.id;try{await $fetch('/api/workspaces/switch',{method:'POST',body:{workspaceId:workspace.id}});window.location.assign('/library')}finally{switchingId.value=''}}
const handleDocumentClick=(event:MouseEvent)=>{if(!root.value?.contains(event.target as Node))close()}
onMounted(()=>document.addEventListener('click',handleDocumentClick))
onBeforeUnmount(()=>document.removeEventListener('click',handleDocumentClick))
</script>
<template><div ref="root" class="workspace-switcher"><button ref="trigger" class="workspace-trigger" type="button" :aria-expanded="open" aria-haspopup="true" @click="open=!open" @keydown.esc="close(true)"><span>{{current?.name??'Content Library'}}</span><svg viewBox="0 0 16 16" aria-hidden="true"><path d="m4 6 4 4 4-4"/></svg></button><div v-if="open" class="workspace-popover" @keydown.esc="close(true)"><p>Workspaces</p><button v-for="workspace in workspaces" :key="workspace.id" type="button" :disabled="Boolean(switchingId)" @click="switchWorkspace(workspace)"><span>{{workspace.name}}<small>{{workspace.role}}</small></span><svg v-if="workspace.id===currentId" viewBox="0 0 16 16" aria-label="Current workspace"><path d="m3 8 3 3 7-7"/></svg></button><div class="workspace-links"><NuxtLink to="/account#new-workspace" @click="close()">Create workspace</NuxtLink><NuxtLink to="/account" @click="close()">Manage workspaces</NuxtLink></div></div></div></template>
<style scoped>.workspace-switcher{position:relative;min-width:0}.workspace-trigger{display:flex;min-width:0;min-height:24px;align-items:center;gap:6px;padding:0;border:0;color:inherit;background:transparent;font:inherit;font-weight:inherit;letter-spacing:inherit;cursor:pointer}.workspace-trigger span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.workspace-trigger svg{width:14px;flex:0 0 auto;fill:none;stroke:currentColor;stroke-width:1.5;transition:rotate 150ms ease-out}.workspace-trigger[aria-expanded=true] svg{rotate:180deg}.workspace-popover{position:absolute;z-index:20;top:calc(100% + 8px);left:0;width:min(280px,calc(100vw - var(--space,24px)*2));padding:8px;border:1px solid rgb(0 0 0/.1);border-radius:18px;background:#fff;box-shadow:0 18px 50px rgb(0 0 0/.14);color:#111;font-size:14px;font-weight:650;letter-spacing:-.01em}.workspace-popover>p{margin:8px 10px;color:rgb(17 17 17/.45);font-size:12px}.workspace-popover>button{display:flex;width:100%;min-height:44px;align-items:center;justify-content:space-between;padding:7px 10px;border:0;border-radius:11px;color:inherit;background:transparent;font:inherit;text-align:left;cursor:pointer}.workspace-popover>button:hover{background:rgb(0 0 0/.055)}.workspace-popover>button:disabled{cursor:wait}.workspace-popover button span{display:grid}.workspace-popover small{color:rgb(17 17 17/.45);font-size:11px;font-weight:550;text-transform:capitalize}.workspace-popover button svg{width:18px;fill:none;stroke:currentColor;stroke-width:1.8}.workspace-links{display:grid;margin-top:6px;padding:6px 10px 4px;border-top:1px solid rgb(0 0 0/.1);gap:8px}.workspace-links a{color:inherit;text-decoration:none}.workspace-trigger:focus-visible,.workspace-popover :is(button,a):focus-visible{outline:2px solid #06f90e;outline-offset:2px}@media(prefers-reduced-motion:reduce){.workspace-trigger svg{transition:none}}</style>
